language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: hK50UQhB8uOoZdCr85dIQjvFPx4mxPmSO49z0DmQy/Y3oXLBm4M4u+ekSNRsURAdvrgLE0xtNxbhaROEm9dBxTHepSfrXtfR0wyCmLcHQm/favpUf+DxiQNpL2ffgEOzJQpxtJ7RNNvyRiD9PpDKH6n7LrQtwOVTbvnTCSubzNlf+gc8S93cblW0m5+UjQVZTY/RZPc0rKh1E8hlJnqjJkY62Hp0CAsC0mJ5nHUEFcAp8fJ4HSabgn+6kXXtcGVs32Byna4b5dDyES1cq/0BQKojVPb58m7IuqB4V4lvKPoxpcYBE2q6DXt0gFXFIV7JYDwFazfeKhxfp6jALjpU6luIaRr+mmE+fG4kmSP1EYqyQSAQOsU6Yzk8OSRnrsdpO3tOvJznu+RTAO8I0jHPstTdMI5ypUWj9E+7PwBEcRGwmz+KrAV7HqaZdZHgmrPxXpJUSVIP5YuLhvIjSLlrNnl/RWP7TsgyNKc6Nes0mEkz7HEyiham0nwUhmvw7xAnyHk3n0m8hqusOq81HUywUQuG6niFZh77pulPCmdxsqPVxpagD3tF+YSeiT01/nQ6xf6s5xhNLZbq9UZUQUFklqR7ddTWfxXqMxT64kGbpgpnT4kqaQbjvtSUqeZZBWD4DwQtFfxMbj0C0y+iAuCFKo0B+kDOOqv4Vp3yYxE7BiM=
  app: lucid-client
  on:
    repo: stevengalvis/lucid-client
