language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: ED+JPPjImIXi5SkyWCRaOKGpg5mcIC1kxIB+0mOfpn+F3V04rAoKyfaZfmnR9mp/z97FjQvmlWY51u0kH7HrNHxQmaRlORnwHEHVjKqWZaFGysKUlc0CT9hkAZOJQu4ASIn1zQBxpIyGr3lzlfWrxHEPiumlrWDKeidRM5FniejpxMKxg8qXemAK/7sepYg4Wx8Wziv3u6+gXhU6I41qNQwXhK6vVVLH1Hw8M8lDe52tCDEDIVHF9ILj8oWhdZ/22Md3vFoS/GCvSQy6htjw9nU2cr/F7gmzqvA6E1n0AJvaIflrCiVCIAPP+fUt//YCuetcwXrcaC1UyvcSSBLjnVA0Gsfhe/V+5+PWZoqiNVeF0PGLSRsFucK+nfnqEzWFcocLH8x41lwv4NYnGpgg+BFhgS9u3BwsZds0yb4J2psNXgeeTF5V/1FF20pRJoPeyULj6vvKBNZY9oGmUYgzFq0VR1g/zks7Imjg4QhUhaohbMwYfsKK8dFGvOgEtnTqIVGrkPQJ4ev+ZlpJu0C9/tpCSw5Ug4UkaFIrJesxzMrqA3wguH9RAICXWNxbx0au0d1qD+evxk1u9QgaWKDjhUvGpLCX3jxpk6eIZwgyxfaRGncy4DB1SG96fAL5AjuwYkHXeGwczGDYqc4fjTzZZgg7ddM+FNUdt/I156lBgwY=
  app: mysterious-island-76316
  on:
    repo: stevengalvis/lucid-client
